name: Deploy RunPod serverless
description: deploy container image to RunPod serverless using RunPod official API
inputs:
  api-key:
    required: true
    description: RunPod API key
  image-name:
    required: true
    description: target container image name
  template-id:
    required: true
    description: RunPod serverless template ID
  submodule-commit-id:
    required: true
    description: target submodule commit ID
runs:
  using: composite
  steps:
    - name: Setup Python environments
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
        architecture: 'x64'
        cache: pip
    - name: Install Python dependencies
      shell: bash
      run: pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
    - name: Deploy image to RunPod Serverless
      shell: bash
      run: >
        python ${GITHUB_ACTION_PATH}/deploy_serverless.py
        --api_key=${{ inputs.api-key }}
        --image_name=${{ inputs.image-name }}
        --template_id=${{ inputs.template-id }}
        --submodule_commit_id="${{ inputs.submodule-commit-id }}"
        | jq -r '.saveTemplate | to_entries[] | "- " + .key + ": " + (.value | tostring)' >> ${GITHUB_STEP_SUMMARY}
