name: create and publish a docker image

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['main']
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    outputs:
      image-tags: ${{ steps.meta.outputs.tags }}
      deploy-env: ${{ env.deploy }}
      release: ${{ env.release }}
    
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}
      
      - name: Set token
        run: echo "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false
          persist-credentials: false

      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          #password: ${{ steps.generate_token.outputs.token }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          #tags: type=raw, value={{date 'YYYYMMDD-hhmmss'}}-{{sha}}
          tags: type=raw, value={{date 'YYYYMMDD-hhmmss'}}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: image=moby/buildkit:latest

      - name: Setup Environments
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            echo "set development environment"
            echo "deploy=dev" >> $GITHUB_ENV
          else
            echo "set production environment"
            echo "deploy=prod" >> $GITHUB_ENV
          fi
          echo "release=${{date 'YYYYMMDD'}}" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BRANCH=${{ github.ref_name }}
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Set image tags for deploy job
        run: echo "image-tags=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT

  deploy-to-runpod:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    environment: ${{ needs.build-and-push-image.outputs.deploy-env }}

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy image to RunPod serverless
        uses: ./.github/actions/deploy_runpod/
        id: deploy
        with:
          api-key: ${{ secrets.RUNPOD_API_KEY }}
          image-name: ${{ needs.build-and-push-image.outputs.image-tags }}
          template-id: ${{ vars.TEMPLATE_ID }}
      
      - name: Set Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: wellflat
          SENTRY_PROJECT: runpod-samples
        with:
          environment: ${{ needs.build-and-push-image.outputs.deploy-env }}
          version: ${{ needs.build-and-push-image.outputs.release }}
      

