name: create and publish a docker image

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['main']
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    outputs:
      image-tags: ${{ steps.meta.outputs.tags }}
      submodule-commit-id: ${{ steps.submodule-id.outputs.id}}
      deploy-env: ${{ env.deploy }}
    
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}
      
      - name: Set token
        run: echo "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      
      - name: Setup SSH Key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.HF_PRIVATE_KEY}}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519
          echo -e "Host hf.co\n\tHostName hf.co\n\tUser git\n\tIdentityFile /home/runner/.ssh/id_ed25519\n\tStrictHostKeyChecking no\n" > /home/runner/.ssh/config
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false
          persist-credentials: false
      
      - name: Set submodule Commit ID
        id: submodule-id
        run: git submodule status sample-models | cut -c 2-41 | xargs echo "id=" >> ${GITHUB_OUTPUT}

      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          #password: ${{ steps.generate_token.outputs.token }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          #tags: type=raw, value={{date 'YYYYMMDD-hhmmss'}}-{{sha}}
          tags: type=raw, value={{date 'YYYYMM'}}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: image=moby/buildkit:latest

      - name: Setup Environments
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            echo "set development environment"
            echo "deploy=dev" >> $GITHUB_ENV
          else
            echo "set production environment"
            echo "deploy=prod" >> $GITHUB_ENV
          fi
          
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Set image tags for deploy job
        run: echo "image-tags=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT

  deploy-to-runpod:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    environment: ${{ needs.build-and-push-image.outputs.deploy-env }}

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test submodule id
        run: echo ${{ needs.build-and-push-image.outputs.submodule-commit-id }}
      
      - name: Deploy image to RunPod serverless
        uses: ./.github/actions/deploy_runpod/
        id: deploy
        with:
          api-key: ${{ secrets.RUNPOD_API_KEY }}
          image-name: ${{ needs.build-and-push-image.outputs.image-tags }}
          template-id: ${{ vars.TEMPLATE_ID }}

      # - name: Setup Python environments
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version-file: "pyproject.toml"
      #     architecture: 'x64'
      #     cache: pip

      # - name: Install dependencies
      #   run: pip install -r src/requirements.txt

      # - name: Deploy image to RunPod Serverless
      #   run: >
      #     python src/deploy_serverless.py
      #     --api_key=${{ secrets.RUNPOD_API_KEY }}
      #     --registry_auth_id=${{ secrets.REGISTRY_AUTH_ID }}
      #     --image_name=${{ needs.build-and-push-image.outputs.image-tags }}
      #     --template_id=${{ vars.TEMPLATE_ID }}
      #     --template_name=${{ vars.TEMPLATE_NAME }}
      #     | jq -r '.saveTemplate | to_entries[] | "- " + .key + ": " + (.value | tostring)' >> ${GITHUB_STEP_SUMMARY}
      

